AWSTemplateFormatVersion: '2010-09-09'
Description: Outputs the time - no SAM required!

Parameters:
  LambdaSourceBucket: 
    Type: String
  LambdaSourceBucketKey:
    Type: String

Resources:
  LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            -
              Action: sts:AssumeRole
              Effect: Allow
              Principal:
                Service: lambda.amazonaws.com

  TimeSamlessFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: LambdaSourceBucket
        S3Key:
          Ref: LambdaSourceBucketKey
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn
      Runtime: nodejs6.10
